layout_spectrum: 0.07235757
typography_spectrum: 0.4088008
color:
  saturation: 0.4429565
  lightness: 0.8814559
  brandStrength: 0.9183844
  rhythmicContrast: 0.4945904
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Chaseschmidt
